name: simple_template_engine
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/wdestroier/simple_template_engine

environment:
  sdk: ^3.5.2

dependencies:
  dart_eval: ^0.7.9

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
